name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Execute deploy script on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 69.62.124.138
          username: yannvr
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/hyperdrift/keep-alive/logs
            cd ~/hyperdrift/keep-alive
            if [ ! -d ".git" ]; then
              git clone git@github.com:yannvr/hyper.git .
            fi
            git checkout main
            git pull origin main
            chmod +x ./scripts/deploy.sh
            ./scripts/deploy.sh
