name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: github-actions # Custom name for the key
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Setup SSH config
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 69.62.124.138 >> ~/.ssh/known_hosts
          # Create SSH config file to specify which key to use
          cat > ~/.ssh/config << 'CONFIG'
          Host 69.62.124.138
            User yannvr
            IdentityFile ~/.ssh/github-actions
            StrictHostKeyChecking no
          CONFIG
          chmod 600 ~/.ssh/config
          ls -la ~/.ssh/

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/github-actions -o StrictHostKeyChecking=no yannvr@69.62.124.138 << 'EOF'
            # Navigate to app directory, creating it if needed
            mkdir -p ~/wakeup
            cd ~/wakeup

            # Pull latest changes or clone repo if not exists
            if [ -d .git ]; then
              git pull
            else
              git clone https://github.com/yannvr/wakeup.git .
            fi

            # Install dependencies
            bun install

            # Setup PM2 configuration if not exists
            if [ ! -f ecosystem.config.js ]; then
              cat > ecosystem.config.js << 'CONFIG'
              module.exports = {
                apps: [{
                  name: "wakeup",
                  script: "bun run index.ts",
                  env: {
                    NODE_ENV: "production",
                  }
                }]
              }
              CONFIG
            fi

            # Create logs directory if it doesn't exist
            mkdir -p logs

            # Start/Restart the app with PM2
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js

            # Save PM2 configuration to start on system boot
            pm2 save
          EOF
