name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy project files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 69.62.124.138
          username: yannvr
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          strip_components: 0
          overwrite: true
          source: "./*,.[!.]*"
          target: "~/hyperdrift/wakeup"

      - name: Execute deploy script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 69.62.124.138
          username: yannvr
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/hyperdrift/wakeup
            chmod +x ~/hyperdrift/wakeup/scripts/deploy.sh
            ./scripts/deploy.sh
