name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy deploy script to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 69.62.124.138
          username: yannvr
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "scripts/deploy.sh"
          target: "~/"

      - name: Execute deploy script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 69.62.124.138
          username: yannvr
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/scripts
            mv ~/deploy.sh ~/scripts/ 2>/dev/null || true
            chmod +x ~/scripts/deploy.sh
            ~/scripts/deploy.sh
